//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroNotas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class note
    {
        public int id { get; set; }
        public Nullable<decimal> note_1 { get; set; }
        public Nullable<decimal> note_2 { get; set; }
        public Nullable<decimal> note_3 { get; set; }
        public Nullable<decimal> note_4 { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_course { get; set; }
    
        public virtual cours cours { get; set; }
        public virtual estudent estudent { get; set; }
    }
}
